lib/quizium_web/router.ex
defmodule QuiziumWeb.Router do
  use QuiziumWeb, :router

  import QuiziumWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {QuiziumWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", QuiziumWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/dashboard", DashboardLive.Index, :index
    live "/quiz", QuizLive.Index, :index

    live "/questions", QuestionLive.Index, :index
    live "/questions/new", QuestionLive.Index, :new
    live "/questions/:id/edit", QuestionLive.Index, :edit
    live "/questions/:id", QuestionLive.Show, :show
    live "/questions/:id/show/edit", QuestionLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", QuiziumWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/sysadmin" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: QuiziumWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", QuiziumWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", QuiziumWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", QuiziumWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/quizium_web/controllers/user_registration_controller.ex
defmodule QuiziumWeb.UserRegistrationController do
  use QuiziumWeb, :controller

  alias Quizium.Accounts
  alias Quizium.Accounts.User
  alias QuiziumWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/quizium_web/views/user_registration_view.ex
defmodule QuiziumWeb.UserRegistrationView do
  use QuiziumWeb, :view
end

lib/quizium_web/templates/user_registration/new.html.heex
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="w-1/2 space-y-8">
    <div>
      <h1 class="mt-8 text-center text-7xl font-extrabold text-gray-900 ">Register</h1>
    </div>
    <.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>
      <input type="hidden" name="remember" value="true" />
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <%= email_input(f, :email,
            required: true,
            class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-orange-500 placeholder-gray-500 text-black-500 rounded-t-md focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-md lg:text-3xl mb-5",
            placeholder: "Email address"
          ) %>
          <%= error_tag(f, :email) %>
        </div>
        <div>
          <%= password_input(f, :password,
            required: true,
            class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-orange-500 placeholder-gray-500 text-black-500 rounded-b-md focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-md lg:text-3xl mb-5",
            placeholder: "Password"
          ) %>
          <%= error_tag(f, :password) %>
        </div>
      </div>

      <div class="flex items-center justify-center">
        <div class="text-sm">
          <%= link("Login", to: Routes.user_session_path(@conn, :new), class: "font-medium text-orange-500 hover:text-orange-500 text-2xl") %> | <%= link("Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "font-medium text-orange-500 hover:text-orange-500 text-2xl ") %>
        </div>
      </div>

      <div>
        <%= submit("Register", class: "group relative w-full flex justify-center py-3 px-4 border border-transparent text-4xl font-medium rounded-md text-white bg-orange-500 hover:bg-orange-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 mt-3") %>
      </div>
    </.form>
  </div>
</div>